server:
  port: 9995

spring:
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:rabbitmq}
    password: ${RABBITMQ_PASSWORD:rabbitmq}
  application:
    name: Mail-Service
  config:
    import: optional:configserver:${CONFIG_SERVER_ENDPOINT:http://localhost:9999}

  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: b4ad5614c0fe1f
    password: 7faa43d61cd232

rabbitmq:
  queue:
    email:
      name: email_queue
  exchange:
    email:
      name: email_exchange
  binding:
    email:
      name: email_routing_key